### ISSUE TITLE
Emails not delivered

### ISSUE THREAD

**Issue by Husseinovich** [tneotia/HLSGrades#1]
Hi tanay, 

Its Hussein here. I am not able to send emails back to you. I keep getting email not delivered errors for the past 3 days.

**Comment by tneotia** [comment]
Okay, I was wondering why I was getting nothing back, but did not want to bother you so much because you said you were on vacation. That is odd, and I have not been receiving emails since July 24th, but did not put too much thought into it. Have you been receiving mine? My account is managed by my dad so I will talk to him when he comes home to troubleshoot what is happening. 

In the meantime if there is something urgent you could comment here.

**Comment by Husseinovich** [comment]
I always receive your emails and have responded back at least 10 emails. I tried using my yahoo and also got back same message. Nothing urgent but a lot of questions here and there, lets link up once you have access to your email or better use a different email client if you cannot resolve this one.

**Comment by tneotia** [comment]
Okay I am very sorry I didn't know this is happening. My dad is looking into it at the moment so hopefully it will be fixed in the next hour. For now you can just forward all the messages to tneotia@gmail.com which is my older email.
